# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest: 
    
    routing_loader: false
      #include_format: false
    format_listener:
      rules:
        - {path: '^/', priorities: ['json'], fallback_format: json}

    exception:
      enabled: true
    view:
      view_response_listener: 'force'
      formats:
        json: true
