#index:
#    path: /
#    controller: App\Controller\DefaultController::index


api_login_check:
    path: /api/login_check

lists:
    type      : annotation
    resource  : App\Controller\ListController
    prefix    : api 

tasks:
    type      : annotation
    resource  : App\Controller\TaskController
    prefix    : api 

notes:
    type      : annotation
    resource  : App\Controller\NoteController
    prefix    : api 